### PR TITLE
Tidied up pod slightly.

### PR DESCRIPTION
**Pull request by manwar**
Hi @shlomif 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by shlomif** [comment]
Hi @manwar ! Text::CSV should be on its own bullet/listitem. Thanks!

**Comment by manwar** [comment]
Re-worked the changes and rebase it.

**Comment by shlomif** [comment]
@manwar : thanks, I'll take a look

**Comment by shlomif** [comment]
@manwar : merged, thanks.

**Comment by shlomif** [comment]
Now part of the 0.6.1 release.

**Pull request merged**
